project_id = "zdxmmwqjvkedddcgucyz"

[functions.send-staff-notification]
verify_jwt = false

[functions.send-submission-notification]
verify_jwt = false

[functions.send-newsletter]
verify_jwt = false

[functions.subscribe-newsletter]
verify_jwt = false

[functions.track-email]
verify_jwt = false
