-- Seed job_listings table with sample internship data
INSERT INTO public.job_listings (title, company, location, job_type, industry, description, requirements, salary, application_url, deadline, is_approved, is_active) VALUES
('Software Engineering Intern', 'Tech Solutions Nigeria', 'Lagos, Nigeria', 'internship', 'Technology', 'Join our engineering team to build scalable web applications. Work with modern technologies and learn from senior developers.', ARRAY['Computer Science student', 'JavaScript/Python knowledge', 'Problem-solving skills'], '₦80,000/month', 'https://techsolutions.ng/careers', '2026-03-31', true, true),
('Marketing Intern', 'Zenith Bank', 'Lagos, Nigeria', 'internship', 'Banking & Finance', 'Assist in developing marketing campaigns, social media management, and brand awareness initiatives for one of Nigeria''s leading banks.', ARRAY['Marketing/Communications student', 'Creative mindset', 'Social media savvy'], '₦100,000/month', 'https://zenithbank.com/careers', '2026-02-28', true, true),
('Data Analytics Intern', 'Andela', 'Remote', 'internship', 'Technology', 'Analyze user data, create dashboards, and help drive data-informed decisions. Perfect for students passionate about data science.', ARRAY['Statistics/Data Science background', 'Excel/SQL knowledge', 'Analytical thinking'], '₦120,000/month', 'https://andela.com/careers', '2026-04-15', true, true),
('Human Resources Intern', 'Dangote Group', 'Lagos, Nigeria', 'internship', 'Manufacturing', 'Support HR operations including recruitment, onboarding, and employee engagement activities at Africa''s largest conglomerate.', ARRAY['HR/Business Admin student', 'Good communication skills', 'Organizational ability'], '₦75,000/month', 'https://dangote.com/careers', '2026-03-15', true, true),
('Product Design Intern', 'Paystack', 'Lagos, Nigeria', 'internship', 'FinTech', 'Design user interfaces and experiences for payment solutions used by thousands of businesses across Africa.', ARRAY['Design student', 'Figma proficiency', 'Portfolio required'], '₦150,000/month', 'https://paystack.com/careers', '2026-02-15', true, true),
('Legal Intern', 'Aluko & Oyebode', 'Lagos, Nigeria', 'internship', 'Legal', 'Gain practical legal experience at one of Nigeria''s leading law firms. Assist with research, documentation, and case preparation.', ARRAY['Law student (300-500 level)', 'Strong research skills', 'Attention to detail'], '₦70,000/month', 'https://aluko-oyebode.com/careers', '2026-03-01', true, true),
('Content Writing Intern', 'Guardian Nigeria', 'Lagos, Nigeria', 'internship', 'Media & Journalism', 'Write articles, conduct interviews, and contribute to digital content for one of Nigeria''s oldest newspapers.', ARRAY['Mass Communication student', 'Excellent writing skills', 'News awareness'], '₦60,000/month', 'https://guardian.ng/careers', '2026-02-20', true, true),
('Accounting Intern', 'PwC Nigeria', 'Lagos, Nigeria', 'internship', 'Consulting', 'Work alongside experienced professionals in audit, tax, and advisory services. Excellent pathway to Big 4 career.', ARRAY['Accounting/Finance student', 'Strong numeracy skills', 'Team player'], '₦100,000/month', 'https://pwc.com/ng/careers', '2026-04-01', true, true),
('UI/UX Research Intern', 'Flutterwave', 'Remote', 'internship', 'FinTech', 'Conduct user research, usability testing, and help shape the future of African payments through user-centered design.', ARRAY['Design/Psychology student', 'Research methodology knowledge', 'Empathy and curiosity'], '₦130,000/month', 'https://flutterwave.com/careers', '2026-03-20', true, true),
('Engineering Intern (Civil)', 'Julius Berger', 'Abuja, Nigeria', 'internship', 'Construction', 'Hands-on experience in major construction projects across Nigeria. Learn from German engineering excellence.', ARRAY['Civil Engineering student', 'AutoCAD knowledge', 'Safety conscious'], '₦90,000/month', 'https://julius-berger.com/careers', '2026-03-10', true, true),
('Investment Banking Intern', 'Stanbic IBTC', 'Lagos, Nigeria', 'internship', 'Banking & Finance', 'Support deal teams in M&A transactions, valuations, and financial modeling. High-intensity learning environment.', ARRAY['Finance/Economics student', 'Excel modeling skills', 'Strong academics (CGPA > 3.5)'], '₦200,000/month', 'https://stanbicibtc.com/careers', '2026-02-10', true, true),
('Brand Management Intern', 'Nigerian Breweries', 'Lagos, Nigeria', 'internship', 'FMCG', 'Support brand strategy and activation for leading beverage brands. Great exposure to consumer goods marketing.', ARRAY['Marketing student', 'Consumer behavior interest', 'Creative thinking'], '₦85,000/month', 'https://nbplc.com/careers', '2026-03-25', true, true)
ON CONFLICT DO NOTHING;